name: 'lintian'
description: 'Run lintian on a Debian package'
inputs:
  package:
    description: 'The package to run lintian on'
    required: true
    default: '*.changes'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package }}
